language: python

python:
    - "2.7"

install:
    pip install tox

env:
  - TOXENV=py27-django-18
  - TOXENV=py27-django-19
  - TOXENV=py27-django-110
  - TOXENV=py27-django-111
  - TOXENV=py34-django-18
  - TOXENV=py34-django-19
  - TOXENV=py34-django-110
  - TOXENV=py34-django-111
  - TOXENV=py35-django-18
  - TOXENV=py35-django-19
  - TOXENV=py35-django-110
  - TOXENV=py35-django-111
  - TOXENV=py35-django-20
  - TOXENV=py36-django-18
  - TOXENV=py36-django-19
  - TOXENV=py36-django-110
  - TOXENV=py36-django-111
  - TOXENV=py36-django-20

matrix:
  fast_finish: true

script:
    tox

branches:
    only:
        - master
        - dev
